---
title: "ps_7"
author: "Connor Riordan"
date: "4/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(stringr)
library(readr)
library(janitor)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(stringr)
library(skimr)
library(purrr)
library(tibble)
library(stringr)
library(forcats)
library(tidyr)
library(broom)
library(gt)
```

## 1A

```{r, chunk_1A, echo = FALSE}
government <- read.csv("data_directory/HSall_members.csv") %>%
  clean_names()

g <- government %>%
  filter(congress == 116) %>%
  filter(chamber == "Senate" | chamber == "House") %>%
  mutate(party = ifelse(party_code == 200, "Republican",
                        ifelse(party_code == 100, "Democrat", 
                               ifelse(party_code == 328, "Independent", "N/A")))) %>%
  filter(!party == "Independent") %>%
  mutate(age = 2019-born) %>%
  mutate(nominate_percentile = percent_rank(nominate_dim1))

g %>%
  skim(nominate_percentile, age) %>%
  print()

```

## 1B

```{r, chunk_1B, echo = FALSE, message = FALSE}
g %>%
  ggplot(aes(age)) + geom_histogram(bins = 30, color = "purple", fill = "dark grey") +
  theme_bw() + labs(
    title = "Distribution of Congressional Ages",
    x = "Age",
    y = "Count"
  ) %>%
  print()

g %>%
  ggplot(aes(nominate_percentile)) + geom_histogram(bins = 30, color = "blue", fill = "dark grey") +
  theme_bw() + labs(
    title = "Distribution of Nomination Percentiles",
    x = "Nomination Percentile",
    y = "Count"
  ) %>%
  print()

```

## 1C

```{r, chunk_1C, echo = FALSE}
g %>%
  summarize(correlation = cor(age, nominate_percentile)) %>%
  print()

# A negative coefficient would indicate that as age increases, the 




```

## 1D

```{r, chunk_1D, echo = FALSE}

scatterplot <- g %>%
  ggplot(aes(age, nominate_percentile, color = party)) + geom_point() + 
  geom_smooth(method = "glm", se = FALSE, color = "black") + geom_smooth(method = "glm", se = FALSE) + 
  scale_color_manual(values = c("blue", "red")) + labs(
    title = "Relationship Between Age and DW Nominate Percentile",
    subtitle = "Higher scores represent more conservative positions",
    x = "Age",
    y = "Percentile Rank (DW Nominee)",
    color = "Party"
  ) + theme_classic()

scatterplot

```

## 2A

```{r, chunk_2A, echo = FALSE}
g %>%
  filter(party_code == 100) %>%
  lm(formula = nominate_percentile ~ age, .) %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, conf.low, conf.high) %>%
  gt() %>%
  tab_header(
    title = "Effect of Age on DW Nominate Percentile",
    subtitle = "Higher percentile suggests more conservative"
  ) %>% cols_label(
    term = "Varibale",
    estimate = "Estimate",
    conf.low = "Lower Bound",
    conf.high = "Upper Bound"
  )

```

## 2B



## 2C



## 3

```{r, chunk_Q3, echo = FALSE}

democrat <- government %>%
  mutate(year = 1787 + (congress*2)) %>%
  mutate(age = year-born) %>%
  mutate(nominate_percentile = percent_rank(nominate_dim1)) %>%
  filter(party_code == 100) %>%
  filter(chamber == "Senate" | chamber == "House") %>%
  group_by(congress) %>%
  nest()


democrat <- democrat %>%
  mutate(mod = map(data, ~ lm(nominate_percentile ~ age, data = .)))
  


```











